; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    br3ttb/PID@^1.2.1
    knolleary/PubSubClient@^2.8
    cyijun/ESP32MQTTClient@^1.1.1
    bblanchon/ArduinoJson@^7.4.1
    Wire
monitor_dtr = 0
monitor_rts = 0

; USB serial upload environment
[env:nodemcu-32s]

; OTA upload environment
[env:nodemcu-32s-ota]
upload_protocol = espota
;upload_port = 192.168.5.17
build_flags = -DOTA_PASSWORD=\"roaster123\"
upload_flags = --auth=roaster123
